-- generated by yaml_to_sql.py
CREATE TABLE IF NOT EXISTS "spacecrafts" (
  "spacecraft_id" INTEGER PRIMARY KEY,
  "primary_name_id" INTEGER,
  "spacecraft_type_id" INTEGER,
  "family_id" INTEGER,
  "model_id" INTEGER,
  "add_element_id" INTEGER,
  "delivery_method_id" INTEGER,
  "mass" REAL,
  "launch_at" TIMESTAMP,
  "cospar_id" INTEGER,
  "launch_id" VARCHAR(8),
  "spaceport_id" INTEGER,
  "on_orbit_at" TIMESTAMP,
  "norad_id" INTEGER,
  "state_id" INTEGER,
  "state_orbit_id" INTEGER,
  "decay_at" TIMESTAMP,
  "orbit_init_altitude" REAL,
  "orbit_init_period" REAL,
  "orbit_init_ecs" REAL,
  "orbit_init_inc" REAL,
  "orb_center_id" INTEGER,
  "launch_method_id" INTEGER,
  "launch_service_id" INTEGER,
  "organization_type_id" INTEGER,
  "platform_id" INTEGER,
  "program_id" INTEGER,
  "develop_country_id" INTEGER,
  "base_spacecraft_id" INTEGER,
  "space_rocket_link" TEXT,
  "nanosats_link" TEXT,
  FOREIGN KEY ("norad_id") REFERENCES "orbital_events"("norad_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("launch_method_id") REFERENCES "launch_methods"("launch_method_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("organization_type_id") REFERENCES "organization_types"("organization_type_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("spacecraft_id") REFERENCES "spacecraft_names"("spacecraft_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("primary_name_id") REFERENCES "spacecraft_names"("name_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("platform_id") REFERENCES "platforms"("platform_id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("program_id") REFERENCES "programs"("program_id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "spacecraft_names" (
  "name_id" INTEGER PRIMARY KEY,
  "spacecraft_id" INTEGER,
  "name" VARCHAR,
  FOREIGN KEY ("spacecraft_id") REFERENCES "spacecrafts"("spacecraft_id")
);

CREATE TABLE IF NOT EXISTS "spacecraft_types" (
  "spacecraft_type_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("spacecraft_type_id") REFERENCES "spacecrafts"("spacecraft_type_id")
);

CREATE TABLE IF NOT EXISTS "spacecraft_families" (
  "family_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  "purpose_id" INTEGER,
  FOREIGN KEY ("family_id") REFERENCES "spacecrafts"("family_id")
);

CREATE TABLE IF NOT EXISTS "spacecrafts_purposes" (
  "purpose_id" INTEGER PRIMARY KEY,
  "purpose_name_en" TEXT,
  "purpose_name_ru" TEXT,
  FOREIGN KEY ("purpose_id") REFERENCES "spacecraft_families"("purpose_id")
);

CREATE TABLE IF NOT EXISTS "spacecraft_models" (
  "model_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  "size" REAL,
  "solar_panels" INTEGER,
  FOREIGN KEY ("model_id") REFERENCES "spacecrafts"("model_id")
);

CREATE TABLE IF NOT EXISTS "add_elements" (
  "add_element_id" INTEGER PRIMARY KEY,
  "has_hood" BOOLEAN,
  "has_large_antenna" BOOLEAN,
  "has_depl_solar_panels" BOOLEAN,
  "has_thruster" BOOLEAN,
  "has_add_mass" BOOLEAN,
  "has_door" BOOLEAN,
  "has_tape" BOOLEAN,
  "has_teather" BOOLEAN,
  "has_cylidner" BOOLEAN,
  "has_rod" BOOLEAN,
  "has_sail" BOOLEAN,
  "has_panel" BOOLEAN,
  "has_balloon" BOOLEAN,
  "has_pyramid" BOOLEAN,
  FOREIGN KEY ("add_element_id") REFERENCES "spacecrafts"("add_element_id")
);

CREATE TABLE IF NOT EXISTS "platforms" (
  "platform_id" INTEGER PRIMARY KEY,
  "name" VARCHAR
);

CREATE TABLE IF NOT EXISTS "states" (
  "state_id" INTEGER PRIMARY KEY,
  "state" VARCHAR,
  FOREIGN KEY ("state_id") REFERENCES "launches"("state_id"),
  FOREIGN KEY ("state_id") REFERENCES "spacecrafts"("state_id")
);

CREATE TABLE IF NOT EXISTS "launches" (
  "launch_id" VARCHAR(8) PRIMARY KEY,
  "launch_at" TIMESTAMP,
  "rocket_id" INTEGER,
  "launchpad_id" INTEGER,
  "state_id" INTEGER
);

CREATE TABLE IF NOT EXISTS "rockets" (
  "rocket_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  "rocket_family_id" INTEGER,
  FOREIGN KEY ("rocket_id") REFERENCES "launches"("rocket_id")
);

CREATE TABLE IF NOT EXISTS "rocket_families" (
  "rocket_family_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("rocket_family_id") REFERENCES "rockets"("rocket_family_id")
);

CREATE TABLE IF NOT EXISTS "spaceports" (
  "spaceport_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  "long" REAL,
  "lat" REAL,
  "country_id" INTEGER,
  FOREIGN KEY ("spaceport_id") REFERENCES "launchpads"("spaceport_id"),
  FOREIGN KEY ("spaceport_id") REFERENCES "spacecrafts"("spaceport_id")
);

CREATE TABLE IF NOT EXISTS "launchpads" (
  "launchpad_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  "spaceport_id" INTEGER,
  "long" REAL,
  "lat" REAL,
  FOREIGN KEY ("launchpad_id") REFERENCES "launches"("launchpad_id")
);

CREATE TABLE IF NOT EXISTS "delivery_methods" (
  "delivery_method_id" INTEGER PRIMARY KEY,
  "dispenser_id" INTEGER,
  "payload_id" INTEGER,
  "delivery_vehicle_id" INTEGER,
  "iss_relation_id" INTEGER,
  "separation_method_id" INTEGER,
  FOREIGN KEY ("delivery_method_id") REFERENCES "spacecrafts"("delivery_method_id")
);

CREATE TABLE IF NOT EXISTS "delivery_vehicles" (
  "delivery_vehicle_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("delivery_vehicle_id") REFERENCES "delivery_methods"("delivery_vehicle_id")
);

CREATE TABLE IF NOT EXISTS "dispensers" (
  "dispenser_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("dispenser_id") REFERENCES "delivery_methods"("dispenser_id")
);

CREATE TABLE IF NOT EXISTS "iss_relations" (
  "iss_relation_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("iss_relation_id") REFERENCES "delivery_methods"("iss_relation_id")
);

CREATE TABLE IF NOT EXISTS "payloads" (
  "payload_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("payload_id") REFERENCES "delivery_methods"("payload_id")
);

CREATE TABLE IF NOT EXISTS "separation_methods" (
  "separation_method_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("separation_method_id") REFERENCES "delivery_methods"("separation_method_id")
);

CREATE TABLE IF NOT EXISTS "base_cs" (
  "base_spacecraft_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("base_spacecraft_id") REFERENCES "spacecrafts"("base_spacecraft_id")
);

CREATE TABLE IF NOT EXISTS "launch_methods" (
  "launch_method_id" INTEGER PRIMARY KEY,
  "name" VARCHAR
);

CREATE TABLE IF NOT EXISTS "states_orbit" (
  "state_orbit_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("state_orbit_id") REFERENCES "spacecrafts"("state_orbit_id")
);

CREATE TABLE IF NOT EXISTS "orb_centers" (
  "orb_center_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  FOREIGN KEY ("orb_center_id") REFERENCES "spacecrafts"("orb_center_id")
);

CREATE TABLE IF NOT EXISTS "programs" (
  "program_id" INTEGER PRIMARY KEY,
  "name" VARCHAR,
  "description" TEXT,
  "link" TEXT
);

CREATE TABLE IF NOT EXISTS "organization_types" (
  "organization_type_id" INTEGER PRIMARY KEY,
  "organization_type_name" VARCHAR
);

CREATE TABLE IF NOT EXISTS "countries" (
  "country_id" INTEGER PRIMARY KEY,
  "en_name_cut" VARCHAR,
  "country_name_en" VARCHAR,
  "country_name_ru" VARCHAR,
  FOREIGN KEY ("country_id") REFERENCES "spacecrafts"("develop_country_id")
);

CREATE TABLE IF NOT EXISTS "launch_services" (
  "launch_service_id" INTEGER PRIMARY KEY,
  "launch_service_name" VARCHAR,
  FOREIGN KEY ("launch_service_id") REFERENCES "spacecrafts"("launch_service_id")
);

CREATE TABLE IF NOT EXISTS "orbital_events" (
  "id" INTEGER PRIMARY KEY,
  "norad_id" INTEGER,
  "eccentricity" REAL,
  "inclination" REAL,
  "mean_anomaly" REAL,
  "perigee_arg" REAL,
  "asend_node_long" REAL,
  "mean_motion" REAL,
  "mean_motion_1der" REAL,
  "mean_motion_2der" REAL,
  "rad_pressure_coef" REAL,
  "event_at" TIMESTAMP,
  "period" REAL,
  "semi_major_axis" REAL,
  "altitude" REAL,
  "perigee_altitude" REAL,
  "apogee_altitude" REAL
);

CREATE INDEX IF NOT EXISTS "cospar_id_index" ON "spacecrafts" ("cospar_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_1" ON "spacecrafts" ("spacecraft_type_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_2" ON "spacecrafts" ("family_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_3" ON "spacecrafts" ("model_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_4" ON "spacecrafts" ("launch_at");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_5" ON "spacecrafts" ("norad_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_6" ON "spacecrafts" ("on_orbit_at");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_7" ON "spacecrafts" ("orb_center_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_8" ON "spacecrafts" ("launch_method_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_9" ON "spacecrafts" ("decay_at");

CREATE INDEX IF NOT EXISTS "platform_id_index" ON "spacecrafts" ("platform_id");

CREATE INDEX IF NOT EXISTS "program_id_index" ON "spacecrafts" ("program_id");

CREATE INDEX IF NOT EXISTS "spacecrafts_index_10" ON "spacecrafts" ("decay_at");

CREATE INDEX IF NOT EXISTS "spacecraft_id_index" ON "spacecraft_names" ("spacecraft_id");

CREATE INDEX IF NOT EXISTS "spacecraft_name_index" ON "spacecraft_names" ("name");

CREATE INDEX IF NOT EXISTS "spacecraft_families_index_0" ON "spacecraft_families" ("purpose_id");

CREATE INDEX IF NOT EXISTS "launches_index_0" ON "launches" ("launch_at");

CREATE INDEX IF NOT EXISTS "launches_index_1" ON "launches" ("rocket_id");

CREATE INDEX IF NOT EXISTS "launches_index_2" ON "launches" ("launchpad_id");

CREATE INDEX IF NOT EXISTS "launchpads_index_0" ON "launchpads" ("spaceport_id");

CREATE INDEX IF NOT EXISTS "dispensers_index_0" ON "delivery_vehicles" ("type_id");

CREATE INDEX IF NOT EXISTS "iss_relations_index_type" ON "iss_relations" ("type_id");

CREATE INDEX IF NOT EXISTS "payloads_index_type" ON "payloads" ("type_id");

CREATE INDEX IF NOT EXISTS "separation_method_index_type" ON "separation_methods" ("type_id");

CREATE INDEX IF NOT EXISTS "norad_event_at_index" ON "orbital_events" ("norad_id", "event_at");

CREATE INDEX IF NOT EXISTS "event_at_index" ON "orbital_events" ("event_at");
